### ISSUE TITLE
Suggestion: Override options when combining rows.

### ISSUE THREAD

**Issue by Vicarium** [svknoe/WH40k-Point-Efficiency-Calculator#17]
When you're using Sum or Pick to combine rows, it'd be extremely useful to have any included options on that row override the options in rows being combined.

For example, if you have a row that's just adding together a unit's weapons, you could also toggle on Devastating Wounds for them in that row's calculation.

If I get a chance I might take a crack at it myself and make a pull request. Any advice?

**Comment by svknoe** [comment]
Interesting suggestion, thank you!

There are two things to consider i) user friendliness and ii) implementation.

i) From a user perspective I like it. I think it would make sense for included options in the "parent row" to override the other rows, but if the parent row has a blank cell, then the corresponding cells in the other rows would be left as is.

ii) From an implementation perspective I'm not sure how it could best be done. Right now damage is calculated row by row. Some rows can be e.g. the sum of other rows. The difficulty with this functionality is that we've invented a sort of "ghost" row - it is neither the original child row nor the parent row. It partly depends on each of them, but it still has to be calculated _somewhere_. I'm not sure where that somewhere would be.

A possible workaround is to set formulas in the input sheet on the child rows referring to the parent row, but it's not quite what you're asking.

---------------

Btw, @TheRealC has been doing a lot of excellent work that is somewhat related to what you're asking. Their work includes global settings, so that you can toggle various armywide rules. It also supports formulas in the input sheets using those toggles.

The work is on the `settings` branch. It hasn't yet been integrated into the main version because of an issue with converting from Excel to google sheets.

**Comment by svknoe** [comment]
The settings functionality from above was added in #19. It's not quite the same as what was requested above, but I hope it will suffice.
